### PR TITLE
Fix cloud plugin install not refreshing

### LINKED ISSUE #2874: Cloud OnCall needs to refresh page on first install
### What went wrong?

**What happened**:
- After creating a new stack in Grafana Cloud when you navigate to OnCall for the first time some initialization takes place.  The UI is stuck with the loading message and does not progress.  If the page is refreshed the interface loads correctly.

Screenshot from 2023-08-24 10-42-43

**What did you expect to happen**:
- After creating a new stack in Grafana Cloud navigation to OnCall should result in the interface loading without the user needing to refresh.

### How do we reproduce it?

1. Create a new stack in Grafana Cloud
2. Log in to newly created stack and navigate to OnCall
3. OnCall is stuck loading until page refresh

### Grafana OnCall Version

r216-v1.3.26

### Product Area

Other

### Grafana OnCall Platform?

I use Grafana Cloud

### User's Browser?

Firefox 116.0.3

### Anything else to add?

_No response_

### PR DESCRIPTION
**Pull request by teodosii**
# What this PR does

## Which issue(s) this PR fixes

#2874

## Checklist

- [ ] Unit, integration, and e2e (if applicable) tests updated
- [ ] Documentation added (or `pr:no public docs` PR label added if not required)
- [ ] `CHANGELOG.md` updated (or `pr:no changelog` PR label added if not required)

### CODE REVIEW

File: grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx [hunk 1]
```diff
@@ -206,4 +201,13 @@ export const Root = observer((props: AppRootProps) => {
       </div>
     </DefaultPageLayout>
   );
+
+  async function runQueuedUpdateData() {
+    try {
+      await store.updateBasicData();
+      setBasicDataLoaded(true);
+    } catch {
+      setTimeout(runQueuedUpdateData, 1000);
```
Comment (joeyorlando) [inline grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx:210]: if this is failing it will loop infinitely, I would consider adding a max number of retries before failing and showing the user some error message
