### PR TITLE
Append grafana styles to head instead of referencing the wrong path

### LINKED ISSUE #672: plugin didn't rewrite url path resources
image

I got a problem on grafana that reversed by nginx which has different root url, example: %(protocol)s://%(domain)s/grafana/. Plugin page opening CSS-file with incorrect url path:

https://host/grafana/public/plugins/grafana-oncall-app/img/grafanaGlobalStyles.css

### PR DESCRIPTION
**Pull request by teodosii**
# What this PR does

Fixed #672 so that we import the css as a whole and add it as a `style` element, instead of relying on path location which can differ if url is rewritten.

## Which issue(s) this PR fixes

#672 

## Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated

### CODE REVIEW

File: grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx [hunk 1]
```diff
@@ -59,6 +59,8 @@ import 'style/responsive.css';
 import { getQueryParams, isTopNavbar } from './GrafanaPluginRootPage.helpers';
 import PluginSetup from './PluginSetup';
 
+import grafanaGlobalStyle from '!raw-loader!img/grafanaGlobalStyles.css';
```
Comment (maskin25) [inline grafana-plugin/src/plugin/GrafanaPluginRootPage.tsx:62]: cool, it's something new for me

**Review by maskin25 — APPROVED** [review]

File: CHANGELOG.md [hunk 2]
```diff
@@ -5,6 +5,12 @@ All notable changes to this project will be documented in this file.
 The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 
+## Unreleased
+
+### Fixed
+
+- Fixed importing of global grafana styles [(672)(<https://github.com/grafana/oncall/issues/672>2>2>2>2>2>)]
```
Comment (joeyorlando) [inline CHANGELOG.md:12]: the URL format here seems funky (`>2>2>2>2>2>` at the end)
